apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
  namespace: rcc-manager
data:
  db_user: "app_user"
  database: "RccManager"
  db_port: "1433"
  db_server: "mysql-service.default.svc.cluster.local"
  key_md5: "UmNjTWFuQGczckAyMDIz"
  redis_host: "redis.rcc-manager.svc.cluster.local"
  redis_port: "6379"
  crypt_key: "KeyRccL0ndr1nA23"
  crypt_iv: "23$2pIRCc$2pIj23"